# Generated by Django 6.0.2 on 2026-02-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Электронная почта"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Страна"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Город"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Улица"
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Номер дома"
                    ),
                ),
                (
                    "name_product",
                    models.CharField(max_length=255, verbose_name="Название продукта"),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Модель"
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата выхода продукта на рынок",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("factory", "Завод"),
                            ("retail", "Розничная сеть"),
                            ("IP", "Индивидуальный предприниматель"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Тип звена",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Уровень сети"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на поставщика"
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Задолженность",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="networks.networknode",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Звено сети",
                "verbose_name_plural": "Звенья сети",
                "ordering": [
                    "name",
                    "email",
                    "country",
                    "city",
                    "name_product",
                    "model",
                    "link",
                    "debt",
                    "created_at",
                ],
            },
        ),
    ]
