# Generated by Django 6.0.2 on 2026-02-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networknode",
            options={
                "ordering": [
                    "name",
                    "email",
                    "country",
                    "city",
                    "name_product",
                    "model",
                    "debt",
                    "created_at",
                ],
                "verbose_name": "Звено сети",
                "verbose_name_plural": "Звенья сети",
            },
        ),
        migrations.RemoveField(
            model_name="networknode",
            name="link",
        ),
    ]
